name: PixelBattle
version: '${version}'
main: com.github.laefye.pixelbattle.PixelBattlePlugin
api-version: 1.19
author: Laefye
softdepend:
  - dynmap
  - PlaceholderAPI
depend:
  - Kublik
commands:
  pixelbattle:
    permission: pixelbattle.pixelbattle
